### PR TITLE
Pills & Mega Health -> of_disable_healthkits

### PR DESCRIPTION
**Pull request by kyokyoknutt**
When of_disable_healthkits is enabled, it disables TF2 healthkits... but not the OF pills & mega health powerup(s). I added checks for both pills and mega healths alongside the regular health kits so NOBODY GETS ANY HEALTH MUHAHAHAHA
I had to tidy up their code and split it into .cpp & header files so I can include the header files in tf_gamerules.
Note: I had to make a new pull request because I'm still getting used to publicly contributing to open source projects and screwed up. I'm sorry for any inconvenience!

### CODE REVIEW

**Comment by IvoryDuke** [comment]
Hi, I will review your changes tomorrow, in the meantime thank you for your contribution.
I have given code a quick look and everything looks sound but I will double check everything more carefully tomorrow

**Comment by IvoryDuke** [comment]
I hope my comments are clear and you agree with the changes.
Thank you for finding the time to work on it.
I would very much appreciate if you could compile it yourself and test it for safety before I include it in the master.

The only real issue I found (redundant #include do not count as issues, we all do that sometime) was that pills and mega were indeed hidden but where still picked up.
That was because func MyTouch() needed usage of ValidTouch() to deny pickup if the item is disabled.

Overall good work 👍

**Comment by kyokyoknutt** [comment]
Thanks for looking through it!
I agree with your changes: this method is so much nicer than what I was doing, lol.
I'll see if it works!

**Comment by kyokyoknutt** [comment]
image
image
we did it reddit
Thank you for your help @IvoryDuke !!!

**Comment by IvoryDuke** [comment]
Alright, I will add it tomorrow after a final test

**Pull request merged**
