### PR TITLE
Added a comprehensive speedometer UI, complete with ConVars

### PR DESCRIPTION
**Pull request by Big-Crab**
Requires the .res files attached.

Demonstration video (As of first commit): https://youtu.be/P68uTYcDA0Q

[SpeedometerUIResFile.zip](https://github.com/KaydemonLP/Open-Fortress-Source/files/4690833/SpeedometerUIResFile.zip)

### CODE REVIEW

**Comment by kyokyoknutt** [comment]
Holy shit, this is sick. Nice!

**Comment by IvoryDuke** [comment]
Nice work, I will get to review the request in details in two days.
Due to the YT compression I have a hard time seeing if the red line above the crosshair, does it only have two fixed positions (slanted to the right at a fixed angle, slanted to the left at a fixed angle) or does it oscillate a bit?

I have written myself a speedometer+strafing help a few months ago and I found that having a graphical element that shows the best mouse position for a Quake 1 style movement is rather excessive, mostly because it will always show that you should place the mouse slightly to the right of left. Unless you move the mouse left and right like a jackass with no thought.
Demonstration of what I mean https://youtu.be/vvS3tlup8NA (00:15 you see a tiny line that shows the supposed best mouse position for the Q1 movement being used).

In light of this, would you be fine with using a simpler graphic (for example left/right arrows to the side of the crosshair) instead of the slanted red line? I personally think it would look less invasive and more effective (feel free to disagree on my point).

// To be performative, we really ought to cache the ConVars upon being changed, rather than doing GetInt/GetBool every frame, but none of the other code seems to bother using it so neither shall I
If you feel like please do the performance caching if it's not too much hassle and I'll see to apply the same approach to the rest of the code in a future update.

I await for your reply and thank you for your contribution

**Comment by Big-Crab** [comment]
> Nice work, I will get to review the request in details in two days.
> Due to the YT compression I have a hard time seeing if the red line above the crosshair, does it only have two fixed positions (slanted to the right at a fixed angle, slanted to the left at a fixed angle) or does it oscillate a bit?
> 
> I have written myself a speedometer+strafing help a few months ago and I found that having a graphical element that shows the best mouse position for a Quake 1 style movement is rather excessive, mostly because it will always show that you should place the mouse slightly to the right of left. Unless you move the mouse left and right like a jackass with no thought.
> Demonstration of what I mean https://youtu.be/vvS3tlup8NA (00:15 you see a tiny line that shows the supposed best mouse position for the Q1 movement being used).
> 
> In light of this, would you be fine with using a simpler graphic (for example left/right arrows to the side of the crosshair) instead of the slanted red line? I personally think it would look less invasive and more effective (feel free to disagree on my point).
> 
> // To be performative, we really ought to cache the ConVars upon being changed, rather than doing GetInt/GetBool every frame, but none of the other code seems to bother using it so neither shall I
> If you feel like please do the performance caching if it's not too much hassle and I'll see to apply the same approach to the rest of the code in a future update.
> 
> I await for your reply and thank you for your contribution

The YT Compression does make it hard to see, but the velocity (red) and input (blue) are shown as 1px thick lines. The blue represents WASD input (Diagonals included), and the red represents the horizontal velocity relative to the view rotation - this is, as you say, a little excessive for typical airstrafing, but I find it's helpful when determining external changes in velocity (Explosions, terrain) and for W-strafing. These are toggle-able, and can now use player colours, so they're not forced in any way.

I'd be happy to add an extra option for the less intrusive arrow system that you describe, but I'm not quite sure what you mean by it - Do you mean showing the bar in your HUD helper that indicates the optimal mouse position? I'd love a draft example of this, it sounds more elegant than my lines!

As for caching convars, I'll have a go at that this evening, since it should be simple in theory.

**Comment by Big-Crab** [comment]
As per @kyokyoknutt's suggestion, I've added drop shadows to the res file, and added a system whereby users can now use the complimentary colour to their colour choice for the UI - a dark-purple Merc should be able to have a brighter yellow speedometer HUD. I've also added this to the speed vectors, which can be toggled to use either the default (red and blue) or the player's colour and its complement. 

[SpeedometerUIResFile.zip](https://github.com/KaydemonLP/Open-Fortress-Source/files/4690827/SpeedometerUIResFile.zip)

**Comment by Big-Crab** [comment]
Followed through on @IvoryDuke's suggestion regarding caching the ConVars. All ConVars that are used in update loops (Paint, OnTick, ShouldDraw) are now cached locally using a callback.
The dropshadow for default (_hud_speedometer_useplayercolour 0_) is black, and foreground now properly resets to off-white when switching back to "0".

_hud_speedometer_useplayercolour 1_ now uses the player's colour for the foreground, and the complementary colour as the background (Black with white, bright yellow with deep purple etc)
_hud_speedometer_useplayercolour 2_ Does the above, but inversed. 
These two options should allow players to use their colours regardless of how bright/dark they are by using the complement between the foreground and background!

Additionally,
_hud_speedometer_vectors_useplayercolour 1_ is now possibly, and uses the aforementioned colour and complement for the input and velocity lines. 0 will use the default red and blue still.

I'm looking to replace the debug-looking vector lines with something more in line with the UI style and more informative/useful. I am currently drafting this, and if it's not too confusing (with branches etc), I'd like to add a ConVar to allow users to zoom in faster with normal weapons (As requested by some users, they'd like it to be instant rather than a motion-sickness inducing Lerp)

**Comment by IvoryDuke** [comment]
Very nice.
I will be rather busy tomorrow but I will surely get to review and approve the merge on Friday.
Everything looks neat and ready to be added, it's just that I want to test everything personally.
Hope this is not a problem.

Concerning the zooming you are free to include it in this pull request, reviewing multiple files is not an issue for me

**Comment by Big-Crab** [comment]
> Very nice.
> I will be rather busy tomorrow but I will surely get to review and approve the merge on Friday.
> Everything looks neat and ready to be added, it's just that I want to test everything personally.
> Hope this is not a problem.
> 
> Concerning the zooming you are free to include it in this pull request, reviewing multiple files is not an issue for me

That's absolutely fine; I've merged the zoom speed branch into this one.
I might add a different visual indicator in place of the velocity and input lines, as you suggested earlier, but I'll only push those once I've completely tested and double checked them.

**Comment by Big-Crab** [comment]
Closed due to new features that the whole thing might as well wait for!
(New request in a few days once it's done)

**Pull request closed without merging**
