### PR TITLE
Null Movement "Script"! + cslide tweaks

### PR DESCRIPTION
**Pull request by kyokyoknutt**
A null movement "script" (in quotes because it's in the code not a cfg file but whatever) has been added and turned on by default. Plus, I added two new convars for server owners to further customize crouch sliding: `of_cslideduration`, to extend, shorten, or eliminate the crouch slide duration cap; and `of_cslidejump` to re-enable jumping while crouched (and csliding) for maximum quasi-tech tacticoolness. Finally, I added help strings to some of the new movement convars.

### CODE REVIEW

**Comment by kyokyoknutt** [comment]
Cleaned up the code a little bit.

**Comment by IvoryDuke** [comment]
Crouch sliding and crouch jumping do not go along together, especially if jump buffer is on.
Remove the cslide crouch jump stuff and I may consider the other,

**Comment by kyokyoknutt** [comment]
Alright. I thought csliding could help you gain speed for bunnyhoping, so I wanted to add an option to make it a bit easier to go back to bhopping after a slide.

**Comment by IvoryDuke** [comment]
To not lose speed all you have to do is let go of the crouch key and then press jump.
You need to account for the fact that you have to have enough Cslide duration for the uncrouching process too

**Comment by kyokyoknutt** [comment]
Removed that convar.

**Pull request merged**
